// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcV8gWvSiSXIOc2SrswmRzelujqMJGdlY',
    appId: '1:1082783837677:web:182a705e30ce9a9fcfcbe4',
    messagingSenderId: '1082783837677',
    projectId: 'foodie-buddy-a49c2',
    authDomain: 'foodie-buddy-a49c2.firebaseapp.com',
    storageBucket: 'foodie-buddy-a49c2.appspot.com',
    measurementId: 'G-FL74KWWPDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5VgRBGzpa-Quu1YEgvVugdbG5itwQp3E',
    appId: '1:1082783837677:android:79034c0b425fa76acfcbe4',
    messagingSenderId: '1082783837677',
    projectId: 'foodie-buddy-a49c2',
    storageBucket: 'foodie-buddy-a49c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7dmX6Fhw8vTcAztwByt5vHkykbNONuiw',
    appId: '1:1082783837677:ios:0b32374aa5328f36cfcbe4',
    messagingSenderId: '1082783837677',
    projectId: 'foodie-buddy-a49c2',
    storageBucket: 'foodie-buddy-a49c2.appspot.com',
    androidClientId: '1082783837677-khjf8t6a9bs3nm6a940mod8bjgccbkrl.apps.googleusercontent.com',
    iosClientId: '1082783837677-rtmourugq09fjhs5d2p3bl533cvv86hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodiebuddyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7dmX6Fhw8vTcAztwByt5vHkykbNONuiw',
    appId: '1:1082783837677:ios:0b32374aa5328f36cfcbe4',
    messagingSenderId: '1082783837677',
    projectId: 'foodie-buddy-a49c2',
    storageBucket: 'foodie-buddy-a49c2.appspot.com',
    androidClientId: '1082783837677-khjf8t6a9bs3nm6a940mod8bjgccbkrl.apps.googleusercontent.com',
    iosClientId: '1082783837677-rtmourugq09fjhs5d2p3bl533cvv86hh.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodiebuddyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcV8gWvSiSXIOc2SrswmRzelujqMJGdlY',
    appId: '1:1082783837677:web:32471b4a0448683dcfcbe4',
    messagingSenderId: '1082783837677',
    projectId: 'foodie-buddy-a49c2',
    authDomain: 'foodie-buddy-a49c2.firebaseapp.com',
    storageBucket: 'foodie-buddy-a49c2.appspot.com',
    measurementId: 'G-WS6QH5YST5',
  );

}